Update geofence.csv
bassmaster187/TeslaLogger pull request #1374
Opened 2024-10-20 13:15 UTC by rowich

- Add SuC Guxhagen
- Fix SuC Lübeck
- Add Tesla GF4 Visitorparking DeC

2024-11-27 21:52 UTC, bassmaster187 commented
Please check the merge conflicts

2024-11-28 07:01 UTC, rowich commented
> Please check the merge conflicts

I already did - there were issues with the nameing, which are still not resolved. I removed the conflicting entry and the last commit was fine (marked green, #338ce5f)

2024-11-28 13:49 UTC, mobbl commented
Since when do we enter AC Chargers into the CSV? Doesn´t make sense to me

2024-11-30 21:33 UTC, mobbl requested changes
Please remove the AC Chargers

2025-07-29 21:20 UTC, closed without merging